### ISSUE TITLE
Not able to write to table with saveas table in spark with s3 as FS path

### ISSUE THREAD

**Issue by HackerHarish95** [AnudeepKonaboina/spear-framework#4]
Sample code:
`
import spark.implicits._
val someDF = Seq(
(1, 1),
(64, 64),
(-27, 27)
).toDF("datastore_id", "table_id")
someDF.write.format("parquet").mode("overwrite").option("path","s3a://ora_timestamps").saveAsTable("ora_timestamps.test")
`

Error:
`21/05/08 11:07:41 WARN hive.HiveExternalCatalog: Could not persist `ora_timestamps`.`test` in a Hive compatible way. Persisting it into Hive metastore in Spark SQL specific format.
org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:720)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$ano…

**Comment by AnudeepKonaboina** [comment]
As this is just a testing env we haven't provided the code of s3 FS with native hive
